### ISSUE TITLE
x-scala-type doesn't accept qualified names in paths section

### ISSUE THREAD

**Issue by dsilvasc** [twilio/guardrail#214]
I can use `x-scala-type: SomeType` in both parameters and definitions.  I can also use `x-scala-type: some.qualified.Type` in definitions -- but not in parameters.  Using that in parameters crashes guardrail:

```
Error: Error attempting to process src/main/resources/swagger-specs/swagger.yaml:

scala.MatchError: some.qualified.Type (of class scala.meta.Type$Select$TypeSelectImpl)
        at com.twilio.guardrail.SwaggerUtil$paths$akkaExtractor$$anonfun$$lessinit$greater$1.$anonfun$apply$9(SwaggerUtil.scala:467)
          ...
        at com.twilio.guardrail.SwaggerUtil$paths$akkaExtractor$$anonfun$$lessinit$greater$1.apply(SwaggerUtil.scala:470)
        at com.twilio.guardrail.SwaggerUtil$paths$akkaExtractor$$anonfun$$lessinit$greater$1.apply(SwaggerUtil.scala:456)
        at com.twilio.guardrail.SwaggerUtil$paths$Extractors.$anonfun$regexSegment$4(SwaggerUtil.scala:419)
        at com.twilio.guardrail.SwaggerUtil$paths$.$anonfun$lookupName$3(SwaggerUtil.scala:367)
          ...

        at com.twilio.guardrail.SwaggerUtil$paths$.com$twilio$guardrail$SwaggerUtil$paths$$lookupName(SwaggerUtil.scala:367)
        at com.twilio.guardrail.SwaggerUtil$paths$Extractors.$anonfun$regexSegment$3(SwaggerUtil.scala:413)
        at com.twilio.guardrail.SwaggerUtil$paths$Extractors.runParse(SwaggerUtil.scala:446)
        at com.twilio.guardrail.SwaggerUtil$paths$.generateUrlAkkaPathExtractors(SwaggerUtil.scala:532)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.pathStrToAkka(AkkaHttpServerGenerator.scala:207)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.$anonfun$generateRoute$10(AkkaHttpServerGenerator.scala:586)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.$anonfun$generateRoute$9(AkkaHttpServerGenerator.scala:585)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.$anonfun$generateRoute$2(AkkaHttpServerGenerator.scala:560)
        at com.twilio.guardrail.generators.AkkaHttpServerGenerator$ServerTermInterp$.generateRoute(AkkaHttpServerGenerator.scala:558)
        ...
```

**Comment by blast-hardcheese** [comment]
Which version? This is likely a `case Type.Name(...)` without a matching `case Type.Select(...)`. Unfortunately, line 467 doesn't turn up anything particularly useful against the [current `master`](https://github.com/twilio/guardrail/blob/a08ae0096382f24d59002e4f3ae7e2fbe5abc512/modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala#L467)

**Comment by dsilvasc** [comment]
Ah, this was on 0.43.0

**Comment by blast-hardcheese** [comment]
as suspected! https://github.com/twilio/guardrail/blob/v0.43.0/modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala#L467

Since we're directly interpolating the type, there's actually no need to constrain to `@ Type.Name(_)` here. If you wouldn't mind opening a PR to remove that, I'll pull it into 0.45.2

**Comment by blast-hardcheese** [comment]
I think the original intent was to exclude `Type.Apply` (`F[A]`), but this is not necessary, as it should be a compiler error, not a crash, and it unintentionally prevents `Type.Select`

**Comment by dsilvasc** [comment]
Ah that makes sense.  Thanks for digging into it.

Opened https://github.com/twilio/guardrail/pull/215 for this.
