### ISSUE TITLE
Cannot access swagger endpoint when using guardrail

### ISSUE THREAD

**Issue by nd-twilio** [twilio/guardrail#730]
👋 team, new to guardrail with swagger. What I observed was that the new resource that is created from guardrail doesn't have @api annotation on it.  So when we try to access the swagger endpoint:
http://{host}:{port}/swagger/#/default it throws this exception

`java.lang.NullPointerException: null
	at io.swagger.core.filter.SpecFilter.filter(SpecFilter.java:52)
	at io.swagger.jaxrs.listing.BaseApiListingResource.process(BaseApiListingResource.java:128)
	at io.swagger.jaxrs.listing.BaseApiListingResource.getListingJsonResponse(BaseApiListingResource.java:155)
	at io.swagger.jaxrs.listing.ApiListingResource.getListing(ApiListingResource.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)` 

Am I missing something?

**Comment by kelnos** [comment]
This is intentional; the `@Api` annotation exists so you can generate a spec file (when you don't already have one) from the resource classes themselves.  With guardrail there's no need for that, because you already have a spec file: the one you've written.  If you want to serve your spec from `/swagger.yaml` or whatever, just include your spec file in your service and serve the static file.
